workspace:
  base: /build
  path: src/github.com/ukhomeoffice/cop-private-workflow-engine

pipeline:
  test:
    image: quay.io/ukhomeofficedigital/openjdk8:latest
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test jacocoTestReport
    when:
      branch: master
      event:
        - push
        - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
    when:
      branch: master
      event:
        - push
        - pull_request

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_name
    commands:
      - docker build -t $${DOCKER_NAME}:$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event:
        - push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event:
        - push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_INTERNAL_CA_URL
      - DEV_NO_LOGGING_URL_PARAMS
      - DEV_NO_LOGGING_BODY
      - DEV_NO_LOGGING_RESPONSE
      - DEV_CA_CERTS
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_SECRET
      - DEV_RESOURCES_IMAGE
      - DEV_PLATFORM_DATA_URL
      - DEV_REDIS_URL
      - DEV_REDIS_PORT
      - DEV_REDIS_TOKEN
      - DEV_GOV_NOTIFY_API_KEY
      - DEV_GOV_NOTIFY_EMAIL_TEMPLATE_ID
      - DEV_GOV_NOTIFY_SMS_TEMPLATE_ID
      - DEV_SPRING
      - DEV_ENGINE_DB_URL
      - DEV_ENGINE_DB_USERNAME
      - DEV_ENGINE_DB_PASSWORD
      - DEV_PUBLIC_UI_PROTOCOL
      - DEV_PUBLIC_UI_TXT_PROTOCOL
      - DEV_PRIVATE_UI_NAME
      - DEV_PRIVATE_POSTGREST_NAME
      - DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - DEV_PRIVATE_TRANSLATION_SERVICE_NAME
      - DEV_PRIVATE_API_SERVER_NAME
      - DEV_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
    commands:
      - export NAME=$${DEV_NAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${DEV_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${DEV_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${DEV_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${DEV_NO_LOGGING_RESPONSE}
      - export CA_CERTS=$${{DEV_CA_CERTS}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${DEV_KEYCLOAK_SECRET}
      - export RESOURCES_IMAGE=$${DEV_RESOURCES_IMAGE}
      - export PLATFORM_DATA_URL=$${DEV_PLATFORM_DATA_URL}
      - export REDIS_URL=$${DEV_REDIS_URL}
      - export REDIS_PORT=$${DEV_REDIS_PORT}
      - export REDIS_TOKEN=$${DEV_REDIS_TOKEN}
      - export GOV_NOTIFY_API_KEY=$${DEV_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${DEV_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${DEV_GOV_NOTIFY_SMS_TEMPLATE_ID}
      - export SPRING=$${DEV_SPRING}
      - export ENGINE_DB_URL=$${DEV_ENGINE_DB_URL}
      - export ENGINE_DB_USERNAME=$${DEV_ENGINE_DB_USERNAME}
      - export ENGINE_DB_PASSWORD=$${DEV_ENGINE_DB_PASSWORD}
      - export PUBLIC_UI_PROTOCOL=$${DEV_PUBLIC_UI_PROTOCOL}
      - export PUBLIC_UI_TXT_PROTOCOL=$${DEV_PUBLIC_UI_TXT_PROTOCOL}
      - export PRIVATE_UI_NAME=$${DEV_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${DEV_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${DEV_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export PRIVATE_API_SERVER_NAME=$${DEV_PRIVATE_API_SERVER_NAME}
      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${DEV_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
    when:
      branch: master
      event:
        - push
        - deployment

#  tag_image_to_quay:
#    image: docker:17.09.1
#    environment:
#      - DOCKER_HOST=tcp://172.17.0.1:2375
#    secrets:
#      - docker_username
#      - docker_password
#      - docker_server
#      - docker_group
#      - docker_name
#    commands:
#    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
#    - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_SHA}
#    - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_SHA}
#    when:
#      event: tag


