pipeline:
  workflow-engine-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t borders-workflow-engine .
    when:
      branch: master
      event: push  
  
  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+borders_central" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag borders-workflow-engine quay.io/ukhomeofficedigital/borders-workflow-engine:$${DRONE_COMMIT_SHA}
      - docker tag borders-workflow-engine quay.io/ukhomeofficedigital/borders-workflow-engine:latest
      - docker push quay.io/ukhomeofficedigital/borders-workflow-engine:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/borders-workflow-engine:latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - INSECURE_SKIP_TLS_VERIFY=true
    secrets:
      - KUBE_TOKEN_DEV
    commands:
      - export KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      - export KUBE_NAMESPACE=bfarch-dev
      - export INSECURE_SKIP_TLS_VERIFY=true
      - export WORKFLOW_ENGINE_RELICAS=2
      - export KUBE_CPU_LIMIT=800m
      - export KUBE_MEMORY_LIMIT=3072Mi
      - export KUBE_TOKEN=$${KUBE_TOKEN_DEV}
      - |
          cd kube
          kd --file deployment.yml \
             --file service.yml
    when:
      event: [deployment, push]
      branch: master

