pipeline:
  test:
    image: digitalpatterns/jdk:1
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test jacocoTestReport
    when:
      event:
        - push
        - pull_request

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event:
        - push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_INTERNAL_CA_URL
      - DEV_NO_LOGGING_URL_PARAMS
      - DEV_NO_LOGGING_BODY
      - DEV_NO_LOGGING_RESPONSE
      - DEV_CA_CERTS
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_SECRET
      - DEV_INT_DOMAIN
      - DEV_EXT_DOMAIN
      - DEV_PROTOCOL
      - DEV_WHITELIST
      - DEV_RESOURCES_IMAGE
      - DEV_PLATFORM_DATA_URL
      - DEV_REF_DATA_URL
      - DEV_REDIS_URL
      - DEV_REDIS_PORT
      - DEV_REDIS_TOKEN
      - DEV_GOV_NOTIFY_API_KEY
      - DEV_GOV_NOTIFY_EMAIL_TEMPLATE_ID
      - DEV_GOV_NOTIFY_SMS_TEMPLATE_ID
      - DEV_SPRING
      - DEV_ENGINE_DB_URL
      - DEV_ENGINE_DB_USERNAME
      - DEV_ENGINE_DB_PASSWORD
      - DEV_PUBLIC_UI_PROTOCOL
      - DEV_PUBLIC_UI_TXT_PROTOCOL
      - DEV_PRIVATE_UI_NAME
      - DEV_PRIVATE_POSTGREST_NAME
      - DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - DEV_PRIVATE_TRANSLATION_SERVICE_NAME
      - DEV_PRIVATE_API_SERVER_NAME
      - DEV_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
    commands:
      - export NAME=$${DEV_NAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${DEV_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${DEV_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${DEV_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${DEV_NO_LOGGING_RESPONSE}
      - export CA_CERTS=$${DEV_CA_CERTS}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${DEV_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${DEV_INT_DOMAIN}
      - export EXT_DOMAIN=$${DEV_EXT_DOMAIN}
      - export PROTOCOL=$${DEV_PROTOCOL}
      - export WHITELIST=$${DEV_WHITELIST}
      - export RESOURCES_IMAGE=$${DEV_RESOURCES_IMAGE}
      - export PLATFORM_DATA_URL=$${DEV_PLATFORM_DATA_URL}
      - export REF_DATA_URL=$${DEV_REF_DATA_URL}
      - export REDIS_URL=$${DEV_REDIS_URL}
      - export REDIS_PORT=$${DEV_REDIS_PORT}
      - export REDIS_TOKEN=$${DEV_REDIS_TOKEN}
      - export GOV_NOTIFY_API_KEY=$${DEV_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${DEV_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${DEV_GOV_NOTIFY_SMS_TEMPLATE_ID}
      - export SPRING=$${DEV_SPRING}
      - export ENGINE_DB_URL=$${DEV_ENGINE_DB_URL}
      - export ENGINE_DB_USERNAME=$${DEV_ENGINE_DB_USERNAME}
      - export ENGINE_DB_PASSWORD=$${DEV_ENGINE_DB_PASSWORD}
      - export PUBLIC_UI_PROTOCOL=$${DEV_PUBLIC_UI_PROTOCOL}
      - export PUBLIC_UI_TXT_PROTOCOL=$${DEV_PUBLIC_UI_TXT_PROTOCOL}
      - export PRIVATE_UI_NAME=$${DEV_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${DEV_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${DEV_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export PRIVATE_API_SERVER_NAME=$${DEV_PRIVATE_API_SERVER_NAME}
      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${DEV_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_NAME
      - STAGING_KUBE_NAMESPACE
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_INTERNAL_CA_URL
      - STAGING_NO_LOGGING_URL_PARAMS
      - STAGING_NO_LOGGING_BODY
      - STAGING_NO_LOGGING_RESPONSE
      - STAGING_CA_CERTS
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_REALM
      - STAGING_KEYCLOAK_SECRET
      - STAGING_INT_DOMAIN
      - STAGING_EXT_DOMAIN
      - STAGING_PROTOCOL
      - STAGING_WHITELIST
      - STAGING_RESOURCES_IMAGE
      - STAGING_PLATFORM_DATA_URL
      - STAGING_REF_DATA_URL
      - STAGING_REDIS_URL
      - STAGING_REDIS_PORT
      - STAGING_REDIS_TOKEN
      - STAGING_GOV_NOTIFY_API_KEY
      - STAGING_GOV_NOTIFY_EMAIL_TEMPLATE_ID
      - STAGING_GOV_NOTIFY_SMS_TEMPLATE_ID
      - STAGING_SPRING
      - STAGING_ENGINE_DB_URL
      - STAGING_ENGINE_DB_USERNAME
      - STAGING_ENGINE_DB_PASSWORD
      - STAGING_PUBLIC_UI_PROTOCOL
      - STAGING_PUBLIC_UI_TXT_PROTOCOL
      - STAGING_PRIVATE_UI_NAME
      - STAGING_PRIVATE_POSTGREST_NAME
      - STAGING_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - STAGING_PRIVATE_TRANSLATION_SERVICE_NAME
      - STAGING_PRIVATE_API_SERVER_NAME
      - STAGING_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
    commands:
      - export NAME=$${STAGING_NAME}
      - export KUBE_NAMESPACE=$${STAGING_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${STAGING_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${STAGING_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${STAGING_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${STAGING_NO_LOGGING_RESPONSE}
      - export CA_CERTS=$${STAGING_CA_CERTS}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${STAGING_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${STAGING_INT_DOMAIN}
      - export EXT_DOMAIN=$${STAGING_EXT_DOMAIN}
      - export PROTOCOL=$${STAGING_PROTOCOL}
      - export WHITELIST=$${STAGING_WHITELIST}
      - export RESOURCES_IMAGE=$${STAGING_RESOURCES_IMAGE}
      - export PLATFORM_DATA_URL=$${STAGING_PLATFORM_DATA_URL}
      - export REF_DATA_URL=$${STAGING_REF_DATA_URL}
      - export REDIS_URL=$${STAGING_REDIS_URL}
      - export REDIS_PORT=$${STAGING_REDIS_PORT}
      - export REDIS_TOKEN=$${STAGING_REDIS_TOKEN}
      - export GOV_NOTIFY_API_KEY=$${STAGING_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${STAGING_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${STAGING_GOV_NOTIFY_SMS_TEMPLATE_ID}
      - export SPRING=$${STAGING_SPRING}
      - export ENGINE_DB_URL=$${STAGING_ENGINE_DB_URL}
      - export ENGINE_DB_USERNAME=$${STAGING_ENGINE_DB_USERNAME}
      - export ENGINE_DB_PASSWORD=$${STAGING_ENGINE_DB_PASSWORD}
      - export PUBLIC_UI_PROTOCOL=$${STAGING_PUBLIC_UI_PROTOCOL}
      - export PUBLIC_UI_TXT_PROTOCOL=$${STAGING_PUBLIC_UI_TXT_PROTOCOL}
      - export PRIVATE_UI_NAME=$${STAGING_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${STAGING_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${STAGING_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${STAGING_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export PRIVATE_API_SERVER_NAME=$${STAGING_PRIVATE_API_SERVER_NAME}
      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${STAGING_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_NAME
      - PRODUCTION_KUBE_NAMESPACE
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_INTERNAL_CA_URL
      - PRODUCTION_NO_LOGGING_URL_PARAMS
      - PRODUCTION_NO_LOGGING_BODY
      - PRODUCTION_NO_LOGGING_RESPONSE
      - PRODUCTION_CA_CERTS
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_KEYCLOAK_SECRET
      - PRODUCTION_INT_DOMAIN
      - PRODUCTION_EXT_DOMAIN
      - PRODUCTION_PROTOCOL
      - PRODUCTION_WHITELIST
      - PRODUCTION_RESOURCES_IMAGE
      - PRODUCTION_PLATFORM_DATA_URL
      - PRODUCTION_REF_DATA_URL
      - PRODUCTION_REDIS_URL
      - PRODUCTION_REDIS_PORT
      - PRODUCTION_REDIS_TOKEN
      - PRODUCTION_GOV_NOTIFY_API_KEY
      - PRODUCTION_GOV_NOTIFY_EMAIL_TEMPLATE_ID
      - PRODUCTION_GOV_NOTIFY_SMS_TEMPLATE_ID
      - PRODUCTION_SPRING
      - PRODUCTION_ENGINE_DB_URL
      - PRODUCTION_ENGINE_DB_USERNAME
      - PRODUCTION_ENGINE_DB_PASSWORD
      - PRODUCTION_PUBLIC_UI_PROTOCOL
      - PRODUCTION_PUBLIC_UI_TXT_PROTOCOL
      - PRODUCTION_PRIVATE_UI_NAME
      - PRODUCTION_PRIVATE_POSTGREST_NAME
      - PRODUCTION_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - PRODUCTION_PRIVATE_TRANSLATION_SERVICE_NAME
      - PRODUCTION_PRIVATE_API_SERVER_NAME
      - PRODUCTION_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
    commands:
      - export NAME=$${PRODUCTION_NAME}
      - export KUBE_NAMESPACE=$${PRODUCTION_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${PRODUCTION_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${PRODUCTION_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${PRODUCTION_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${PRODUCTION_NO_LOGGING_RESPONSE}
      - export CA_CERTS=$${PRODUCTION_CA_CERTS}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${PRODUCTION_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${PRODUCTION_INT_DOMAIN}
      - export EXT_DOMAIN=$${PRODUCTION_EXT_DOMAIN}
      - export PROTOCOL=$${PRODUCTION_PROTOCOL}
      - export WHITELIST=$${PRODUCTION_WHITELIST}
      - export RESOURCES_IMAGE=$${PRODUCTION_RESOURCES_IMAGE}
      - export PLATFORM_DATA_URL=$${PRODUCTION_PLATFORM_DATA_URL}
      - export REF_DATA_URL=$${PRODUCTION_REF_DATA_URL}
      - export REDIS_URL=$${PRODUCTION_REDIS_URL}
      - export REDIS_PORT=$${PRODUCTION_REDIS_PORT}
      - export REDIS_TOKEN=$${PRODUCTION_REDIS_TOKEN}
      - export GOV_NOTIFY_API_KEY=$${PRODUCTION_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${PRODUCTION_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${PRODUCTION_GOV_NOTIFY_SMS_TEMPLATE_ID}
      - export SPRING=$${PRODUCTION_SPRING}
      - export ENGINE_DB_URL=$${PRODUCTION_ENGINE_DB_URL}
      - export ENGINE_DB_USERNAME=$${PRODUCTION_ENGINE_DB_USERNAME}
      - export ENGINE_DB_PASSWORD=$${PRODUCTION_ENGINE_DB_PASSWORD}
      - export PUBLIC_UI_PROTOCOL=$${PRODUCTION_PUBLIC_UI_PROTOCOL}
      - export PUBLIC_UI_TXT_PROTOCOL=$${PRODUCTION_PUBLIC_UI_TXT_PROTOCOL}
      - export PRIVATE_UI_NAME=$${PRODUCTION_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${PRODUCTION_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${PRODUCTION_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${PRODUCTION_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export PRIVATE_API_SERVER_NAME=$${PRODUCTION_PRIVATE_API_SERVER_NAME}
      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${PRODUCTION_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment

