---
kind: pipeline
type: kubernetes
name: matrix-1

platform:
  os: linux
  arch: amd64

steps:
- name: synch_dev_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: DEV_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: dev
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_PUBLIC_TOKEN
  when:
    event:
    - promote
    target:
    - secrets

- name: synch_staging_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: STAGING_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: staging
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_PUBLIC_TOKEN
  when:
    event:
    - promote
    target:
    - secrets

- name: synch_production_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: production
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_PUBLIC_TOKEN
  when:
    event:
    - promote
    target:
    - secrets

- name: build
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t cop-private-workflow-engine:$${DRONE_COMMIT_SHA} .
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push

- name: vulnerability-scan
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: cop-private-workflow-engine:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: true
    SERVICE_URL: http://anchore-submission-server:10080
    TOLERATE: low
  when:
    branch:
    - master
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    tags: ${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  when:
    branch:
    - master
    event:
    - push

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
  - export ENGINE_SPRING_PROFILES_ACTIVE="dev"
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
  - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=8m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    ENGINE_AWS_ACCESS_KEY_ID:
      from_secret: DEV_ENGINE_AWS_ACCESS_KEY_ID
    ENGINE_AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_ENGINE_AWS_SECRET_ACCESS_KEY
    ENGINE_IMAGE:
      from_secret: DEV_ENGINE_IMAGE
    ENGINE_NAME:
      from_secret: DEV_ENGINE_NAME
    ENGINE_URL:
      from_secret: DEV_ENGINE_URL
    KUBE_NAMESPACE:
      from_secret: DEV_KUBE_NAMESPACE_PRIVATE_COP
    KUBE_SERVER:
      from_secret: DEV_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: DEV_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
  when:
    branch:
    - master
    event:
    - push

- name: deploy_to_staging
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
  - export ENGINE_SPRING_PROFILES_ACTIVE="staging"
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
  - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=8m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    ENGINE_AWS_ACCESS_KEY_ID:
      from_secret: STAGING_ENGINE_AWS_ACCESS_KEY_ID
    ENGINE_AWS_SECRET_ACCESS_KEY:
      from_secret: STAGING_ENGINE_AWS_SECRET_ACCESS_KEY
    ENGINE_IMAGE:
      from_secret: STAGING_ENGINE_IMAGE
    ENGINE_NAME:
      from_secret: STAGING_ENGINE_NAME
    ENGINE_URL:
      from_secret: STAGING_ENGINE_URL
    KUBE_NAMESPACE:
      from_secret: STAGING_KUBE_NAMESPACE_PRIVATE_COP
    KUBE_SERVER:
      from_secret: STAGING_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: STAGING_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
  when:
    event:
    - promote
    target:
    - staging

- name: deploy_to_production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
  - export ENGINE_SPRING_PROFILES_ACTIVE="production"
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
  - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=8m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    ENGINE_AWS_ACCESS_KEY_ID:
      from_secret: PRODUCTION_ENGINE_AWS_ACCESS_KEY_ID
    ENGINE_AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_ENGINE_AWS_SECRET_ACCESS_KEY
    ENGINE_IMAGE:
      from_secret: PRODUCTION_ENGINE_IMAGE
    ENGINE_NAME:
      from_secret: PRODUCTION_ENGINE_NAME
    ENGINE_URL:
      from_secret: PRODUCTION_ENGINE_URL
    KUBE_NAMESPACE:
      from_secret: PRODUCTION_KUBE_NAMESPACE_PRIVATE_COP
    KUBE_SERVER:
      from_secret: PRODUCTION_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: PRODUCTION_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
  when:
    event:
    - promote
    target:
    - production

- name: create-change-desc-production
  pull: if-not-exists
  image: docker:git
  commands:
  - git show --name-only >> $SNOW_DESC_FILE
  when:
    event:
    - promote
    target:
    - production

- name: open-snow-change-production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/snowtify:latest
  environment:
    SNOW_ENDPOINT:
      from_secret: PRODUCTION_SERVICE_NOW_URL
    SNOW_EXTERNAL_ID: ${DRONE_REPO}:${DRONE_COMMIT_SHA}
    SNOW_PROD_PASS:
      from_secret: PRODUCTION_SERVICE_NOW_PASSWORD
    SNOW_PROD_USER:
      from_secret: PRODUCTION_SERVICE_NOW_USERNAME
  when:
    event:
    - promote
    target:
    - production

- name: complete-snow-change-production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/snowtify:latest
  settings:
    comments: Successful deployment of ${DRONE_REPO}:${DRONE_COMMIT_SHA}
    deployment_outcome: success
  environment:
    SNOW_ENDPOINT:
      from_secret: PRODUCTION_SERVICE_NOW_URL
    SNOW_PROD_PASS:
      from_secret: PRODUCTION_SERVICE_NOW_PASSWORD
    SNOW_PROD_USER:
      from_secret: PRODUCTION_SERVICE_NOW_USERNAME
  when:
    event:
    - promote
    status:
    - success
    target:
    - production

- name: cancel-snow-change-production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/snowtify:latest
  settings:
    comments: Failed deployment of ${DRONE_REPO}:${DRONE_COMMIT_SHA}
    deployment_outcome: fail
  environment:
    SNOW_ENDPOINT:
      from_secret: PRODUCTION_SERVICE_NOW_URL
    SNOW_PROD_PASS:
      from_secret: PRODUCTION_SERVICE_NOW_PASSWORD
    SNOW_PROD_USER:
      from_secret: PRODUCTION_SERVICE_NOW_USERNAME
  when:
    event:
    - promote
    status:
    - failure
    target:
    - production

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - push
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
  - /anchore-submission server
  environment:
    ANCHORE_URL: acp-anchore.acp.homeoffice.gov.uk
    REGISTRY_URL: acp-ephemeral-registry.acp.homeoffice.gov.uk
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

...
