pipeline:
  workflow-engine-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t borders-workflow-engine .
    when:
      branch: master
      event: push  
  
  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+borders_central" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag borders-workflow-engine quay.io/ukhomeofficedigital/borders-workflow-engine:$${DRONE_COMMIT_SHA}
      - docker tag borders-workflow-engine quay.io/ukhomeofficedigital/borders-workflow-engine:latest
      - docker push quay.io/ukhomeofficedigital/borders-workflow-engine:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/borders-workflow-engine:latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      - KUBE_NAMESPACE=bfarch-dev
      - INSECURE_SKIP_TLS_VERIFY=true
      - WORKFLOW_ENGINE_RELICAS=2
      - KUBE_CPU_LIMIT=800m
      - KUBE_MEMORY_LIMIT=3072Mi
    commands:
      - cd kube
      - kd -f deployment.yml -f service.yml
    secrets:
      - kube_token_dev
    when:
      event: [deployment, push]
      branch: master

