pipeline:
  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_staging_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=staging
    secrets:
      - source: STAGING_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=production
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  test:
    image: digitalpatterns/jdk:1
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test jacocoTestReport
    when:
      event:
        - push
        - pull_request

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-private-workflow-engine:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: DEV_KUBE_SERVER
      target: KUBE_SERVER
    - source: DEV_KUBE_TOKEN
      target: KUBE_TOKEN
    - source: DEV_WHITELIST
      target: WHITELIST
    - source: DEV_KEYCLOAK_URL
      target: KEYCLOAK_URL
    - source: DEV_KEYCLOAK_REALM
      target: KEYCLOAK_REALM
    - source: PROTOCOL_HTTPS
      target: KEYCLOAK_PROTOCOL
    - source: NGINX_IMAGE
      target: NGINX_IMAGE
    - source: NGINX_TAG
      target: NGINX_TAG
    - source: DEV_REDIS_URL
      target: REDIS_URL
    - source: DEV_REDIS_TOKEN
      target: REDIS_TOKEN
    - source: DEV_REDIS_SSL
      target: REDIS_SSL
    - source: DEV_GOV_NOTIFY_API_KEY
      target: GOV_NOTIFY_API_KEY
    - source: DEV_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
      target: GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
    - source: DEV_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
      target: GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
    - source: DEV_WWW_URL
      target: WWW_URL
    - source: PROTOCOL_HTTPS
      target: WWW_PROTOCOL
    - source: PROTOCOL_HTTPS
      target: WWW_UI_PROTOCOL
    - source: PROTOCOL_AWBS
      target: WWW_UI_TXT_PROTOCOL
    - source: PROTOCOL_HTTPS
      target: API_COP_PROTOCOL
    - source: DEV_API_COP_URL
      target: API_COP_URL
    - source: PROTOCOL_HTTPS
      target: API_FORM_PROTOCOL
    - source: DEV_API_FORM_URL
      target: API_FORM_URL
    - source: PROTOCOL_HTTPS
      target: API_REF_PROTOCOL
    - source: DEV_API_REF_URL
      target: API_REF_URL
    - source: PROTOCOL_POSTGRES
      target: DB_ENGINE_PROTOCOL
    - source: PROTOCOL_JDBC
      target: DB_ENGINE_JDBC_PROTOCOL
    - source: DEV_DB_ENGINE_PORT
      target: DB_ENGINE_PORT
    - source: DEV_DB_ENGINE_HOSTNAME
      target: DB_ENGINE_HOSTNAME
    - source: DEV_DB_ENGINE_OPTIONS
      target: DB_ENGINE_OPTIONS
    - source: DEV_DB_ENGINE_DRIVER
      target: DB_ENGINE_DRIVER
    - source: DEV_DB_ENGINE_TYPE
      target: DB_ENGINE_TYPE
    - source: DEV_DB_ENGINE_JDBC_OPTIONS
      target: DB_ENGINE_JDBC_OPTIONS
    - source: DEV_DB_ENGINE_DEFAULT_USERNAME
      target: DB_ENGINE_DEFAULT_USERNAME
    - source: DEV_DB_ENGINE_DEFAULT_DBNAME
      target: DB_ENGINE_DEFAULT_DBNAME
    - source: DEV_DB_ENGINE_DEFAULT_PASSWORD
      target: DB_ENGINE_DEFAULT_PASSWORD
    - source: DEV_ENGINE_NAME
      target: ENGINE_NAME
    - source: DEV_ENGINE_URL
      target: ENGINE_URL
    - source: DEV_ENGINE_IMAGE
      target: ENGINE_IMAGE
    - source: DEV_ENGINE_KEYCLOAK_CLIENT_ID
      target: ENGINE_KEYCLOAK_CLIENT_ID
    - source: DEV_ENGINE_KEYCLOAK_CLIENT_SECRET
      target: ENGINE_KEYCLOAK_CLIENT_SECRET
    - source: DEV_ENGINE_SPRING_PROFILES_ACTIVE
      target: ENGINE_SPRING_PROFILES_ACTIVE
    - source: DEV_KUBE_NAMESPACE_PRIVATE_COP
      target: KUBE_NAMESPACE
    - source: ENGINE_PORT
      target: ENGINE_PORT
    - source: DEV_ENGINE_JAVA_OPTS
      target: ENGINE_JAVA_OPTS
    - source: DEV_ENGINE_CORS
      target: ENGINE_CORS
    - source: DEV_ENGINE_ENCRYPTION_PASSPHRASE
      target: ENGINE_ENCRYPTION_PASSPHRASE
    - source: DEV_ENGINE_ENCRYPTION_SALT
      target: ENGINE_ENCRYPTION_SALT
    - source: DEV_ENGINE_AWS_ACCESS_KEY_ID
      target: ENGINE_AWS_ACCESS_KEY_ID
    - source: DEV_ENGINE_AWS_SECRET_ACCESS_KEY
      target: ENGINE_AWS_SECRET_ACCESS_KEY
    - source: DEV_ENGINE_S3_CASE_BUCKET_NAME
      target: ENGINE_S3_CASE_BUCKET_NAME
    - source: DEV_ENGINE_S3_BUCKET_NAME_PREFIX
      target: ENGINE_S3_BUCKET_NAME_PREFIX
    commands:
      - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  vulnerability-scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: Dockerfile
    image_name: cop-private-workflow-engine:${DRONE_COMMIT_SHA}
    local_image: true
    tolerate: low
    fail_on_detection: false
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: STAGING_KUBE_SERVER
      target: KUBE_SERVER
    - source: STAGING_KUBE_TOKEN
      target: KUBE_TOKEN
    - source: STAGING_WHITELIST
      target: WHITELIST
    - source: STAGING_KEYCLOAK_URL
      target: KEYCLOAK_URL
    - source: STAGING_KEYCLOAK_REALM
      target: KEYCLOAK_REALM
    - source: PROTOCOL_HTTPS
      target: KEYCLOAK_PROTOCOL
    - source: NGINX_IMAGE
      target: NGINX_IMAGE
    - source: NGINX_TAG
      target: NGINX_TAG
    - source: STAGING_REDIS_URL
      target: REDIS_URL
    - source: STAGING_REDIS_TOKEN
      target: REDIS_TOKEN
    - source: STAGING_REDIS_SSL
      target: REDIS_SSL
    - source: STAGING_GOV_NOTIFY_API_KEY
      target: GOV_NOTIFY_API_KEY
    - source: STAGING_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
      target: GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
    - source: STAGING_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
      target: GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
    - source: STAGING_WWW_URL
      target: WWW_URL
    - source: PROTOCOL_HTTPS
      target: WWW_PROTOCOL
    - source: PROTOCOL_HTTPS
      target: WWW_UI_PROTOCOL
    - source: PROTOCOL_AWBS
      target: WWW_UI_TXT_PROTOCOL
    - source: PROTOCOL_HTTPS
      target: API_COP_PROTOCOL
    - source: STAGING_API_COP_URL
      target: API_COP_URL
    - source: PROTOCOL_HTTPS
      target: API_FORM_PROTOCOL
    - source: STAGING_API_FORM_URL
      target: API_FORM_URL
    - source: PROTOCOL_HTTPS
      target: API_REF_PROTOCOL
    - source: STAGING_API_REF_URL
      target: API_REF_URL
    - source: PROTOCOL_POSTGRES
      target: DB_ENGINE_PROTOCOL
    - source: PROTOCOL_JDBC
      target: DB_ENGINE_JDBC_PROTOCOL
    - source: STAGING_DB_ENGINE_PORT
      target: DB_ENGINE_PORT
    - source: STAGING_DB_ENGINE_HOSTNAME
      target: DB_ENGINE_HOSTNAME
    - source: STAGING_DB_ENGINE_OPTIONS
      target: DB_ENGINE_OPTIONS
    - source: STAGING_DB_ENGINE_DRIVER
      target: DB_ENGINE_DRIVER
    - source: STAGING_DB_ENGINE_TYPE
      target: DB_ENGINE_TYPE
    - source: STAGING_DB_ENGINE_JDBC_OPTIONS
      target: DB_ENGINE_JDBC_OPTIONS
    - source: STAGING_DB_ENGINE_DEFAULT_USERNAME
      target: DB_ENGINE_DEFAULT_USERNAME
    - source: STAGING_DB_ENGINE_DEFAULT_DBNAME
      target: DB_ENGINE_DEFAULT_DBNAME
    - source: STAGING_DB_ENGINE_DEFAULT_PASSWORD
      target: DB_ENGINE_DEFAULT_PASSWORD
    - source: STAGING_ENGINE_NAME
      target: ENGINE_NAME
    - source: STAGING_ENGINE_URL
      target: ENGINE_URL
    - source: STAGING_ENGINE_IMAGE
      target: ENGINE_IMAGE
    - source: STAGING_ENGINE_KEYCLOAK_CLIENT_ID
      target: ENGINE_KEYCLOAK_CLIENT_ID
    - source: STAGING_ENGINE_KEYCLOAK_CLIENT_SECRET
      target: ENGINE_KEYCLOAK_CLIENT_SECRET
    - source: STAGING_ENGINE_SPRING_PROFILES_ACTIVE
      target: ENGINE_SPRING_PROFILES_ACTIVE
    - source: STAGING_KUBE_NAMESPACE_PRIVATE_COP
      target: KUBE_NAMESPACE
    - source: ENGINE_PORT
      target: ENGINE_PORT
    - source: STAGING_ENGINE_JAVA_OPTS
      target: ENGINE_JAVA_OPTS
    - source: STAGING_ENGINE_CORS
      target: ENGINE_CORS
    - source: STAGING_ENGINE_ENCRYPTION_PASSPHRASE
      target: ENGINE_ENCRYPTION_PASSPHRASE
    - source: STAGING_ENGINE_ENCRYPTION_SALT
      target: ENGINE_ENCRYPTION_SALT
    - source: STAGING_ENGINE_AWS_ACCESS_KEY_ID
      target: ENGINE_AWS_ACCESS_KEY_ID
    - source: STAGING_ENGINE_AWS_SECRET_ACCESS_KEY
      target: ENGINE_AWS_SECRET_ACCESS_KEY
    - source: STAGING_ENGINE_S3_CASE_BUCKET_NAME
      target: ENGINE_S3_CASE_BUCKET_NAME
    - source: STAGING_ENGINE_S3_BUCKET_NAME_PREFIX
      target: ENGINE_S3_BUCKET_NAME_PREFIX
    commands:
      - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: PRODUCTION_KUBE_SERVER
      target: KUBE_SERVER
    - source: PRODUCTION_KUBE_TOKEN
      target: KUBE_TOKEN
    - source: PRODUCTION_WHITELIST
      target: WHITELIST
    - source: PRODUCTION_KEYCLOAK_URL
      target: KEYCLOAK_URL
    - source: PRODUCTION_KEYCLOAK_REALM
      target: KEYCLOAK_REALM
    - source: PROTOCOL_HTTPS
      target: KEYCLOAK_PROTOCOL
    - source: NGINX_IMAGE
      target: NGINX_IMAGE
    - source: NGINX_TAG
      target: NGINX_TAG
    - source: PRODUCTION_REDIS_URL
      target: REDIS_URL
    - source: PRODUCTION_REDIS_TOKEN
      target: REDIS_TOKEN
    - source: PRODUCTION_REDIS_SSL
      target: REDIS_SSL
    - source: PRODUCTION_GOV_NOTIFY_API_KEY
      target: GOV_NOTIFY_API_KEY
    - source: PRODUCTION_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
      target: GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
    - source: PRODUCTION_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
      target: GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
    - source: PRODUCTION_WWW_URL
      target: WWW_URL
    - source: PROTOCOL_HTTPS
      target: WWW_PROTOCOL
    - source: PROTOCOL_HTTPS
      target: WWW_UI_PROTOCOL
    - source: PROTOCOL_AWBS
      target: WWW_UI_TXT_PROTOCOL
    - source: PROTOCOL_HTTPS
      target: API_COP_PROTOCOL
    - source: PRODUCTION_API_COP_URL
      target: API_COP_URL
    - source: PROTOCOL_HTTPS
      target: API_FORM_PROTOCOL
    - source: PRODUCTION_API_FORM_URL
      target: API_FORM_URL
    - source: PROTOCOL_HTTPS
      target: API_REF_PROTOCOL
    - source: PRODUCTION_API_REF_URL
      target: API_REF_URL
    - source: PROTOCOL_POSTGRES
      target: DB_ENGINE_PROTOCOL
    - source: PROTOCOL_JDBC
      target: DB_ENGINE_JDBC_PROTOCOL
    - source: PRODUCTION_DB_ENGINE_PORT
      target: DB_ENGINE_PORT
    - source: PRODUCTION_DB_ENGINE_HOSTNAME
      target: DB_ENGINE_HOSTNAME
    - source: PRODUCTION_DB_ENGINE_OPTIONS
      target: DB_ENGINE_OPTIONS
    - source: PRODUCTION_DB_ENGINE_DRIVER
      target: DB_ENGINE_DRIVER
    - source: PRODUCTION_DB_ENGINE_TYPE
      target: DB_ENGINE_TYPE
    - source: PRODUCTION_DB_ENGINE_JDBC_OPTIONS
      target: DB_ENGINE_JDBC_OPTIONS
    - source: PRODUCTION_DB_ENGINE_DEFAULT_USERNAME
      target: DB_ENGINE_DEFAULT_USERNAME
    - source: PRODUCTION_DB_ENGINE_DEFAULT_DBNAME
      target: DB_ENGINE_DEFAULT_DBNAME
    - source: PRODUCTION_DB_ENGINE_DEFAULT_PASSWORD
      target: DB_ENGINE_DEFAULT_PASSWORD
    - source: PRODUCTION_ENGINE_NAME
      target: ENGINE_NAME
    - source: PRODUCTION_ENGINE_URL
      target: ENGINE_URL
    - source: PRODUCTION_ENGINE_IMAGE
      target: ENGINE_IMAGE
    - source: PRODUCTION_ENGINE_KEYCLOAK_CLIENT_ID
      target: ENGINE_KEYCLOAK_CLIENT_ID
    - source: PRODUCTION_ENGINE_KEYCLOAK_CLIENT_SECRET
      target: ENGINE_KEYCLOAK_CLIENT_SECRET
    - source: PRODUCTION_ENGINE_SPRING_PROFILES_ACTIVE
      target: ENGINE_SPRING_PROFILES_ACTIVE
    - source: PRODUCTION_KUBE_NAMESPACE_PRIVATE_COP
      target: KUBE_NAMESPACE
    - source: ENGINE_PORT
      target: ENGINE_PORT
    - source: PRODUCTION_ENGINE_JAVA_OPTS
      target: ENGINE_JAVA_OPTS
    - source: PRODUCTION_ENGINE_CORS
      target: ENGINE_CORS
    - source: PRODUCTION_ENGINE_ENCRYPTION_PASSPHRASE
      target: ENGINE_ENCRYPTION_PASSPHRASE
    - source: PRODUCTION_ENGINE_ENCRYPTION_SALT
      target: ENGINE_ENCRYPTION_SALT
    - source: PRODUCTION_ENGINE_AWS_ACCESS_KEY_ID
      target: ENGINE_AWS_ACCESS_KEY_ID
    - source: PRODUCTION_ENGINE_AWS_SECRET_ACCESS_KEY
      target: ENGINE_AWS_SECRET_ACCESS_KEY
    - source: PRODUCTION_ENGINE_S3_CASE_BUCKET_NAME
      target: ENGINE_S3_CASE_BUCKET_NAME
    - source: PRODUCTION_ENGINE_S3_BUCKET_NAME_PREFIX
      target: ENGINE_S3_BUCKET_NAME_PREFIX
    commands:
      - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
