pipeline:
  workflow-engine-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t borders-workflow-engine .
    when:
      branch: master
      event: push  
  
  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+borders_central" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag borders-workflow-engine quay.io/ukhomeofficedigital/borders-workflow-engine:$${DRONE_COMMIT_SHA}
      - docker tag borders-workflow-engine quay.io/ukhomeofficedigital/borders-workflow-engine:latest
      - docker push quay.io/ukhomeofficedigital/borders-workflow-engine:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/borders-workflow-engine:latest
    when:
      branch: master
      event: push
    