pipeline:
  test:
    image: quay.io/digitalpatterns/jdk:master
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test jacocoTestReport
    when:
      event:
        - push
        - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event:
        - push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_INTERNAL_CA_URL
      - DEV_NO_LOGGING_URL_PARAMS
      - DEV_NO_LOGGING_BODY
      - DEV_NO_LOGGING_RESPONSE
      - DEV_CA_CERTS
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_SECRET
      - DEV_INT_DOMAIN
      - DEV_EXT_DOMAIN
      - DEV_PROTOCOL
      - DEV_WHITELIST
      - DEV_RESOURCES_IMAGE
      - DEV_PLATFORM_DATA_URL
      - DEV_REDIS_URL
      - DEV_REDIS_PORT
      - DEV_REDIS_TOKEN
      - DEV_GOV_NOTIFY_API_KEY
      - DEV_GOV_NOTIFY_EMAIL_TEMPLATE_ID
      - DEV_GOV_NOTIFY_SMS_TEMPLATE_ID
      - DEV_SPRING
      - DEV_ENGINE_DB_URL
      - DEV_ENGINE_DB_USERNAME
      - DEV_ENGINE_DB_PASSWORD
      - DEV_PUBLIC_UI_PROTOCOL
      - DEV_PUBLIC_UI_TXT_PROTOCOL
      - DEV_PRIVATE_UI_NAME
      - DEV_PRIVATE_POSTGREST_NAME
      - DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - DEV_PRIVATE_TRANSLATION_SERVICE_NAME
      - DEV_PRIVATE_API_SERVER_NAME
      - DEV_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
      - DEV_UPTIME
    commands:
      - export NAME=$${DEV_NAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${DEV_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${DEV_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${DEV_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${DEV_NO_LOGGING_RESPONSE}
      - export CA_CERTS=$${DEV_CA_CERTS}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${DEV_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${DEV_INT_DOMAIN}
      - export EXT_DOMAIN=$${DEV_EXT_DOMAIN}
      - export PROTOCOL=$${DEV_PROTOCOL}
      - export WHITELIST=$${DEV_WHITELIST}
      - export RESOURCES_IMAGE=$${DEV_RESOURCES_IMAGE}
      - export PLATFORM_DATA_URL=$${DEV_PLATFORM_DATA_URL}
      - export REDIS_URL=$${DEV_REDIS_URL}
      - export REDIS_PORT=$${DEV_REDIS_PORT}
      - export REDIS_TOKEN=$${DEV_REDIS_TOKEN}
      - export GOV_NOTIFY_API_KEY=$${DEV_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${DEV_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${DEV_GOV_NOTIFY_SMS_TEMPLATE_ID}
      - export SPRING=$${DEV_SPRING}
      - export ENGINE_DB_URL=$${DEV_ENGINE_DB_URL}
      - export ENGINE_DB_USERNAME=$${DEV_ENGINE_DB_USERNAME}
      - export ENGINE_DB_PASSWORD=$${DEV_ENGINE_DB_PASSWORD}
      - export PUBLIC_UI_PROTOCOL=$${DEV_PUBLIC_UI_PROTOCOL}
      - export PUBLIC_UI_TXT_PROTOCOL=$${DEV_PUBLIC_UI_TXT_PROTOCOL}
      - export PRIVATE_UI_NAME=$${DEV_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${DEV_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${DEV_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export PRIVATE_API_SERVER_NAME=$${DEV_PRIVATE_API_SERVER_NAME}
      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${DEV_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
      - export IMAGE_TAG=$${DRONE_BUILD_NUMBER}
      - export UPTIME=$${DEV_UPTIME}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event:
        - push

#  deploy_to_test:
#    image: quay.io/ukhomeofficedigital/kd
#    secrets:
#      - TEST_NAME
#      - TEST_KUBE_NAMESPACE
#      - TEST_KUBE_SERVER
#      - TEST_KUBE_TOKEN
#      - TEST_INTERNAL_CA_URL
#      - TEST_NO_LOGGING_URL_PARAMS
#      - TEST_NO_LOGGING_BODY
#      - TEST_NO_LOGGING_RESPONSE
#      - TEST_CA_CERTS
#      - TEST_KEYCLOAK_URL
#      - TEST_KEYCLOAK_REALM
#      - TEST_KEYCLOAK_SECRET
#      - TEST_INT_DOMAIN
#      - TEST_EXT_DOMAIN
#      - TEST_PROTOCOL
#      - TEST_WHITELIST
#      - TEST_RESOURCES_IMAGE
#      - TEST_PLATFORM_DATA_URL
#      - TEST_REDIS_URL
#      - TEST_REDIS_PORT
#      - TEST_REDIS_TOKEN
#      - TEST_GOV_NOTIFY_API_KEY
#      - TEST_GOV_NOTIFY_EMAIL_TEMPLATE_ID
#      - TEST_GOV_NOTIFY_SMS_TEMPLATE_ID
#      - TEST_SPRING
#      - TEST_ENGINE_DB_URL
#      - TEST_ENGINE_DB_USERNAME
#      - TEST_ENGINE_DB_PASSWORD
#      - TEST_PUBLIC_UI_PROTOCOL
#      - TEST_PUBLIC_UI_TXT_PROTOCOL
#      - TEST_PRIVATE_UI_NAME
#      - TEST_PRIVATE_POSTGREST_NAME
#      - TEST_PRIVATE_WORKFLOW_EXECUTOR_NAME
#      - TEST_PRIVATE_TRANSLATION_SERVICE_NAME
#      - TEST_PRIVATE_API_SERVER_NAME
#      - TEST_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
#      - TEST_UPTIME
#    commands:
#      - export NAME=$${TEST_NAME}
#      - export KUBE_NAMESPACE=$${TEST_KUBE_NAMESPACE}
#      - export KUBE_SERVER=$${TEST_KUBE_SERVER}
#      - export KUBE_TOKEN=$${TEST_KUBE_TOKEN}
#      - export INTERNAL_CA_URL=$${TEST_INTERNAL_CA_URL}
#      - export NO_LOGGING_URL_PARAMS=$${TEST_NO_LOGGING_URL_PARAMS}
#      - export NO_LOGGING_BODY=$${TEST_NO_LOGGING_BODY}
#      - export NO_LOGGING_RESPONSE=$${TEST_NO_LOGGING_RESPONSE}
#      - export CA_CERTS=$${TEST_CA_CERTS}
#      - export KEYCLOAK_URL=$${TEST_KEYCLOAK_URL}
#      - export KEYCLOAK_REALM=$${TEST_KEYCLOAK_REALM}
#      - export KEYCLOAK_SECRET=$${TEST_KEYCLOAK_SECRET}
#      - export INT_DOMAIN=$${TEST_INT_DOMAIN}
#      - export EXT_DOMAIN=$${TEST_EXT_DOMAIN}
#      - export PROTOCOL=$${TEST_PROTOCOL}
#      - export WHITELIST=$${TEST_WHITELIST}
#      - export RESOURCES_IMAGE=$${TEST_RESOURCES_IMAGE}
#      - export PLATFORM_DATA_URL=$${TEST_PLATFORM_DATA_URL}
#      - export REDIS_URL=$${TEST_REDIS_URL}
#      - export REDIS_PORT=$${TEST_REDIS_PORT}
#      - export REDIS_TOKEN=$${TEST_REDIS_TOKEN}
#      - export GOV_NOTIFY_API_KEY=$${TEST_GOV_NOTIFY_API_KEY}
#      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${TEST_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
#      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${TEST_GOV_NOTIFY_SMS_TEMPLATE_ID}
#      - export SPRING=$${TEST_SPRING}
#      - export ENGINE_DB_URL=$${TEST_ENGINE_DB_URL}
#      - export ENGINE_DB_USERNAME=$${TEST_ENGINE_DB_USERNAME}
#      - export ENGINE_DB_PASSWORD=$${TEST_ENGINE_DB_PASSWORD}
#      - export PUBLIC_UI_PROTOCOL=$${TEST_PUBLIC_UI_PROTOCOL}
#      - export PUBLIC_UI_TXT_PROTOCOL=$${TEST_PUBLIC_UI_TXT_PROTOCOL}
#      - export PRIVATE_UI_NAME=$${TEST_PRIVATE_UI_NAME}
#      - export PRIVATE_POSTGREST_NAME=$${TEST_PRIVATE_POSTGREST_NAME}
#      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${TEST_PRIVATE_WORKFLOW_EXECUTOR_NAME}
#      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${TEST_PRIVATE_TRANSLATION_SERVICE_NAME}
#      - export PRIVATE_API_SERVER_NAME=$${TEST_PRIVATE_API_SERVER_NAME}
#      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${TEST_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
#      - export IMAGE_TAG=$${DRONE_BUILD_NUMBER}
#      - export UPTIME=$${TEST_UPTIME}
#      - kd --insecure-skip-tls-verify -f kube/secret.yml
#      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
#      - kd --insecure-skip-tls-verify -f kube/service.yml
#      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
#      - kd --insecure-skip-tls-verify -f kube/ingress.yml
#    when:
#      branch: master
#      event:
#        - push

  deploy_to_demo:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEMO_NAME
      - DEMO_KUBE_NAMESPACE
      - DEMO_KUBE_SERVER
      - DEMO_KUBE_TOKEN
      - DEMO_INTERNAL_CA_URL
      - DEMO_NO_LOGGING_URL_PARAMS
      - DEMO_NO_LOGGING_BODY
      - DEMO_NO_LOGGING_RESPONSE
      - DEMO_CA_CERTS
      - DEMO_KEYCLOAK_URL
      - DEMO_KEYCLOAK_REALM
      - DEMO_KEYCLOAK_SECRET
      - DEMO_INT_DOMAIN
      - DEMO_EXT_DOMAIN
      - DEMO_PROTOCOL
      - DEMO_WHITELIST
      - DEMO_RESOURCES_IMAGE
      - DEMO_PLATFORM_DATA_URL
      - DEMO_REDIS_URL
      - DEMO_REDIS_PORT
      - DEMO_REDIS_TOKEN
      - DEMO_GOV_NOTIFY_API_KEY
      - DEMO_GOV_NOTIFY_EMAIL_TEMPLATE_ID
      - DEMO_GOV_NOTIFY_SMS_TEMPLATE_ID
      - DEMO_SPRING
      - DEMO_ENGINE_DB_URL
      - DEMO_ENGINE_DB_USERNAME
      - DEMO_ENGINE_DB_PASSWORD
      - DEMO_PUBLIC_UI_PROTOCOL
      - DEMO_PUBLIC_UI_TXT_PROTOCOL
      - DEMO_PRIVATE_UI_NAME
      - DEMO_PRIVATE_POSTGREST_NAME
      - DEMO_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - DEMO_PRIVATE_TRANSLATION_SERVICE_NAME
      - DEMO_PRIVATE_API_SERVER_NAME
      - DEMO_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME
      - DEMO_UPTIME
    commands:
      - export NAME=$${DEMO_NAME}
      - export KUBE_NAMESPACE=$${DEMO_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEMO_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEMO_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${DEMO_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${DEMO_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${DEMO_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${DEMO_NO_LOGGING_RESPONSE}
      - export CA_CERTS=$${DEMO_CA_CERTS}
      - export KEYCLOAK_URL=$${DEMO_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEMO_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${DEMO_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${DEMO_INT_DOMAIN}
      - export EXT_DOMAIN=$${DEMO_EXT_DOMAIN}
      - export PROTOCOL=$${DEMO_PROTOCOL}
      - export WHITELIST=$${DEMO_WHITELIST}
      - export RESOURCES_IMAGE=$${DEMO_RESOURCES_IMAGE}
      - export PLATFORM_DATA_URL=$${DEMO_PLATFORM_DATA_URL}
      - export REDIS_URL=$${DEMO_REDIS_URL}
      - export REDIS_PORT=$${DEMO_REDIS_PORT}
      - export REDIS_TOKEN=$${DEMO_REDIS_TOKEN}
      - export GOV_NOTIFY_API_KEY=$${DEMO_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_EMAIL_TEMPLATE_ID=$${DEMO_GOV_NOTIFY_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_SMS_TEMPLATE_ID=$${DEMO_GOV_NOTIFY_SMS_TEMPLATE_ID}
      - export SPRING=$${DEMO_SPRING}
      - export ENGINE_DB_URL=$${DEMO_ENGINE_DB_URL}
      - export ENGINE_DB_USERNAME=$${DEMO_ENGINE_DB_USERNAME}
      - export ENGINE_DB_PASSWORD=$${DEMO_ENGINE_DB_PASSWORD}
      - export PUBLIC_UI_PROTOCOL=$${DEMO_PUBLIC_UI_PROTOCOL}
      - export PUBLIC_UI_TXT_PROTOCOL=$${DEMO_PUBLIC_UI_TXT_PROTOCOL}
      - export PRIVATE_UI_NAME=$${DEMO_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${DEMO_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${DEMO_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${DEMO_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export PRIVATE_API_SERVER_NAME=$${DEMO_PRIVATE_API_SERVER_NAME}
      - export PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME=$${DEMO_PRIVATE_SERVICE_INTERFACE_GATEWAY_NAME}
      - export IMAGE_TAG=$${IMAGE_TAG}
      - export UPTIME=$${DEMO_UPTIME}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
    when:
      environment:
        - demo
      event:
        - deployment
