pipeline:
  test:
    image: digitalpatterns/jdk:1
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test jacocoTestReport
    when:
      event:
        - push
        - pull_request

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: DEV_QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: DEV_QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_QUAY_USERNAME
      - DEV_QUAY_PASSWORD
      - DEV_WHITELIST
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_PROTOCOL
      - DEV_NGINX_IMAGE
      - DEV_NGINX_TAG
      - DEV_REDIS_URL
      - DEV_REDIS_TOKEN
      - DEV_REDIS_SSL
      - DEV_GOV_NOTIFY_API_KEY
      - DEV_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
      - DEV_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
      - DEV_WWW_URL
      - DEV_WWW_PROTOCOL
      - DEV_WWW_UI_PROTOCOL
      - DEV_WWW_UI_TXT_PROTOCOL
      - DEV_API_COP_PROTOCOL
      - DEV_API_COP_URL
      - DEV_API_REF_PROTOCOL
      - DEV_API_REF_URL
      - DEV_DB_ENGINE_PROTOCOL
      - DEV_DB_ENGINE_JDBC_PROTOCOL
      - DEV_DB_ENGINE_PORT
      - DEV_DB_ENGINE_HOSTNAME
      - DEV_DB_ENGINE_OPTIONS
      - DEV_DB_ENGINE_DRIVER
      - DEV_DB_ENGINE_TYPE
      - DEV_DB_ENGINE_JDBC_OPTIONS
      - DEV_DB_ENGINE_DEFAULT_USERNAME
      - DEV_DB_ENGINE_DEFAULT_DBNAME
      - DEV_DB_ENGINE_DEFAULT_PASSWORD
      - DEV_ENGINE_NAME
      - DEV_ENGINE_URL
      - DEV_ENGINE_IMAGE
      - DEV_ENGINE_KEYCLOAK_CLIENT_ID
      - DEV_ENGINE_KEYCLOAK_CLIENT_SECRET
      - DEV_ENGINE_SPRING_PROFILES_ACTIVE
      - DEV_ENGINE_KUBE_NAMESPACE
      - DEV_ENGINE_PORT
      - DEV_ENGINE_JAVA_OPTS
      - DEV_ENGINE_CORS
    commands:
      - export KUBE_NAMESPACE=$${DEV_ENGINE_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export QUAY_USERNAME=$${DEV_QUAY_USERNAME}
      - export QUAY_PASSWORD=$${DEV_QUAY_PASSWORD}
      - export WHITELIST=$${DEV_WHITELIST}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${DEV_KEYCLOAK_PROTOCOL}
      - export NGINX_IMAGE=$${DEV_NGINX_IMAGE}
      - export NGINX_TAG=$${DEV_NGINX_TAG}
      - export REDIS_URL=$${DEV_REDIS_URL}
      - export REDIS_TOKEN=$${DEV_REDIS_TOKEN}
      - export REDIS_SSL=$${DEV_REDIS_SSL}
      - export GOV_NOTIFY_API_KEY=$${DEV_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID=$${DEV_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID=$${DEV_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}
      - export WWW_URL=$${DEV_WWW_URL}
      - export WWW_PROTOCOL=$${DEV_WWW_PROTOCOL}
      - export WWW_UI_PROTOCOL=$${DEV_WWW_UI_PROTOCOL}
      - export WWW_UI_TXT_PROTOCOL=$${DEV_WWW_UI_TXT_PROTOCOL}
      - export API_COP_PROTOCOL=$${DEV_API_COP_PROTOCOL}
      - export API_COP_URL=$${DEV_API_COP_URL}
      - export API_REF_PROTOCOL=$${DEV_API_REF_PROTOCOL}
      - export API_REF_URL=$${DEV_API_REF_URL}
      - export DB_ENGINE_PROTOCOL=$${DEV_DB_ENGINE_PROTOCOL}
      - export DB_ENGINE_JDBC_PROTOCOL=$${DEV_DB_ENGINE_JDBC_PROTOCOL}
      - export DB_ENGINE_PORT=$${DEV_DB_ENGINE_PORT}
      - export DB_ENGINE_HOSTNAME=$${DEV_DB_ENGINE_HOSTNAME}
      - export DB_ENGINE_OPTIONS=$${DEV_DB_ENGINE_OPTIONS}
      - export DB_ENGINE_DRIVER=$${DEV_DB_ENGINE_DRIVER}
      - export DB_ENGINE_TYPE=$${DEV_DB_ENGINE_TYPE}
      - export DB_ENGINE_JDBC_OPTIONS=$${DEV_DB_ENGINE_JDBC_OPTIONS}
      - export DB_ENGINE_DEFAULT_USERNAME=$${DEV_DB_ENGINE_DEFAULT_USERNAME}
      - export DB_ENGINE_DEFAULT_DBNAME=$${DEV_DB_ENGINE_DEFAULT_DBNAME}
      - export DB_ENGINE_DEFAULT_PASSWORD=$${DEV_DB_ENGINE_DEFAULT_PASSWORD}
      - export ENGINE_NAME=$${DEV_ENGINE_NAME}
      - export ENGINE_URL=$${DEV_ENGINE_URL}
      - export ENGINE_IMAGE=$${DEV_ENGINE_IMAGE}
      - export ENGINE_KEYCLOAK_CLIENT_ID=$${DEV_ENGINE_KEYCLOAK_CLIENT_ID}
      - export ENGINE_KEYCLOAK_CLIENT_SECRET=$${DEV_ENGINE_KEYCLOAK_CLIENT_SECRET}
      - export ENGINE_SPRING_PROFILES_ACTIVE=$${DEV_ENGINE_SPRING_PROFILES_ACTIVE}
      - export ENGINE_KUBE_NAMESPACE=$${DEV_ENGINE_KUBE_NAMESPACE}
      - export ENGINE_PORT=$${DEV_ENGINE_PORT}
      - export ENGINE_JAVA_OPTS=$${DEV_ENGINE_JAVA_OPTS}
      - export ENGINE_CORS=$${DEV_ENGINE_CORS}
      - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_QUAY_USERNAME
      - STAGING_QUAY_PASSWORD
      - STAGING_WHITELIST
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_REALM
      - STAGING_KEYCLOAK_PROTOCOL
      - STAGING_NGINX_IMAGE
      - STAGING_NGINX_TAG
      - STAGING_REDIS_URL
      - STAGING_REDIS_TOKEN
      - STAGING_REDIS_SSL
      - STAGING_GOV_NOTIFY_API_KEY
      - STAGING_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
      - STAGING_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
      - STAGING_WWW_URL
      - STAGING_WWW_PROTOCOL
      - STAGING_WWW_UI_PROTOCOL
      - STAGING_WWW_UI_TXT_PROTOCOL
      - STAGING_API_COP_PROTOCOL
      - STAGING_API_COP_URL
      - STAGING_API_REF_PROTOCOL
      - STAGING_API_REF_URL
      - STAGING_DB_ENGINE_PROTOCOL
      - STAGING_DB_ENGINE_JDBC_PROTOCOL
      - STAGING_DB_ENGINE_PORT
      - STAGING_DB_ENGINE_HOSTNAME
      - STAGING_DB_ENGINE_OPTIONS
      - STAGING_DB_ENGINE_DRIVER
      - STAGING_DB_ENGINE_TYPE
      - STAGING_DB_ENGINE_JDBC_OPTIONS
      - STAGING_DB_ENGINE_DEFAULT_USERNAME
      - STAGING_DB_ENGINE_DEFAULT_DBNAME
      - STAGING_DB_ENGINE_DEFAULT_PASSWORD
      - STAGING_ENGINE_NAME
      - STAGING_ENGINE_URL
      - STAGING_ENGINE_IMAGE
      - STAGING_ENGINE_KEYCLOAK_CLIENT_ID
      - STAGING_ENGINE_KEYCLOAK_CLIENT_SECRET
      - STAGING_ENGINE_SPRING_PROFILES_ACTIVE
      - STAGING_ENGINE_KUBE_NAMESPACE
      - STAGING_ENGINE_PORT
      - STAGING_ENGINE_JAVA_OPTS
      - STAGING_ENGINE_CORS
    commands:
      - export KUBE_NAMESPACE=$${STAGING_ENGINE_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export QUAY_USERNAME=$${STAGING_QUAY_USERNAME}
      - export QUAY_PASSWORD=$${STAGING_QUAY_PASSWORD}
      - export WHITELIST=$${STAGING_WHITELIST}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${STAGING_KEYCLOAK_PROTOCOL}
      - export NGINX_IMAGE=$${STAGING_NGINX_IMAGE}
      - export NGINX_TAG=$${STAGING_NGINX_TAG}
      - export REDIS_URL=$${STAGING_REDIS_URL}
      - export REDIS_TOKEN=$${STAGING_REDIS_TOKEN}
      - export REDIS_SSL=$${STAGING_REDIS_SSL}
      - export GOV_NOTIFY_API_KEY=$${STAGING_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID=$${STAGING_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID=$${STAGING_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}
      - export WWW_URL=$${STAGING_WWW_URL}
      - export WWW_PROTOCOL=$${STAGING_WWW_PROTOCOL}
      - export WWW_UI_PROTOCOL=$${STAGING_WWW_UI_PROTOCOL}
      - export WWW_UI_TXT_PROTOCOL=$${STAGING_WWW_UI_TXT_PROTOCOL}
      - export API_COP_PROTOCOL=$${STAGING_API_COP_PROTOCOL}
      - export API_COP_URL=$${STAGING_API_COP_URL}
      - export API_REF_PROTOCOL=$${STAGING_API_REF_PROTOCOL}
      - export API_REF_URL=$${STAGING_API_REF_URL}
      - export DB_ENGINE_PROTOCOL=$${STAGING_DB_ENGINE_PROTOCOL}
      - export DB_ENGINE_JDBC_PROTOCOL=$${STAGING_DB_ENGINE_JDBC_PROTOCOL}
      - export DB_ENGINE_PORT=$${STAGING_DB_ENGINE_PORT}
      - export DB_ENGINE_HOSTNAME=$${STAGING_DB_ENGINE_HOSTNAME}
      - export DB_ENGINE_OPTIONS=$${STAGING_DB_ENGINE_OPTIONS}
      - export DB_ENGINE_DRIVER=$${STAGING_DB_ENGINE_DRIVER}
      - export DB_ENGINE_TYPE=$${STAGING_DB_ENGINE_TYPE}
      - export DB_ENGINE_JDBC_OPTIONS=$${STAGING_DB_ENGINE_JDBC_OPTIONS}
      - export DB_ENGINE_DEFAULT_USERNAME=$${STAGING_DB_ENGINE_DEFAULT_USERNAME}
      - export DB_ENGINE_DEFAULT_DBNAME=$${STAGING_DB_ENGINE_DEFAULT_DBNAME}
      - export DB_ENGINE_DEFAULT_PASSWORD=$${STAGING_DB_ENGINE_DEFAULT_PASSWORD}
      - export ENGINE_NAME=$${STAGING_ENGINE_NAME}
      - export ENGINE_URL=$${STAGING_ENGINE_URL}
      - export ENGINE_IMAGE=$${STAGING_ENGINE_IMAGE}
      - export ENGINE_KEYCLOAK_CLIENT_ID=$${STAGING_ENGINE_KEYCLOAK_CLIENT_ID}
      - export ENGINE_KEYCLOAK_CLIENT_SECRET=$${STAGING_ENGINE_KEYCLOAK_CLIENT_SECRET}
      - export ENGINE_SPRING_PROFILES_ACTIVE=$${STAGING_ENGINE_SPRING_PROFILES_ACTIVE}
      - export ENGINE_KUBE_NAMESPACE=$${STAGING_ENGINE_KUBE_NAMESPACE}
      - export ENGINE_PORT=$${STAGING_ENGINE_PORT}
      - export ENGINE_JAVA_OPTS=$${STAGING_ENGINE_JAVA_OPTS}
      - export ENGINE_CORS=$${STAGING_ENGINE_CORS}
      - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_QUAY_USERNAME
      - PRODUCTION_QUAY_PASSWORD
      - PRODUCTION_WHITELIST
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_KEYCLOAK_PROTOCOL
      - PRODUCTION_NGINX_IMAGE
      - PRODUCTION_NGINX_TAG
      - PRODUCTION_REDIS_URL
      - PRODUCTION_REDIS_TOKEN
      - PRODUCTION_REDIS_SSL
      - PRODUCTION_GOV_NOTIFY_API_KEY
      - PRODUCTION_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID
      - PRODUCTION_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID
      - PRODUCTION_WWW_URL
      - PRODUCTION_WWW_PROTOCOL
      - PRODUCTION_WWW_UI_PROTOCOL
      - PRODUCTION_WWW_UI_TXT_PROTOCOL
      - PRODUCTION_API_COP_PROTOCOL
      - PRODUCTION_API_COP_URL
      - PRODUCTION_API_REF_PROTOCOL
      - PRODUCTION_API_REF_URL
      - PRODUCTION_DB_ENGINE_PROTOCOL
      - PRODUCTION_DB_ENGINE_JDBC_PROTOCOL
      - PRODUCTION_DB_ENGINE_PORT
      - PRODUCTION_DB_ENGINE_HOSTNAME
      - PRODUCTION_DB_ENGINE_OPTIONS
      - PRODUCTION_DB_ENGINE_DRIVER
      - PRODUCTION_DB_ENGINE_TYPE
      - PRODUCTION_DB_ENGINE_JDBC_OPTIONS
      - PRODUCTION_DB_ENGINE_DEFAULT_USERNAME
      - PRODUCTION_DB_ENGINE_DEFAULT_DBNAME
      - PRODUCTION_DB_ENGINE_DEFAULT_PASSWORD
      - PRODUCTION_ENGINE_NAME
      - PRODUCTION_ENGINE_URL
      - PRODUCTION_ENGINE_IMAGE
      - PRODUCTION_ENGINE_KEYCLOAK_CLIENT_ID
      - PRODUCTION_ENGINE_KEYCLOAK_CLIENT_SECRET
      - PRODUCTION_ENGINE_SPRING_PROFILES_ACTIVE
      - PRODUCTION_ENGINE_KUBE_NAMESPACE
      - PRODUCTION_ENGINE_PORT
      - PRODUCTION_ENGINE_JAVA_OPTS
      - PRODUCTION_ENGINE_CORS
    commands:
      - export KUBE_NAMESPACE=$${PRODUCTION_ENGINE_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export QUAY_USERNAME=$${PRODUCTION_QUAY_USERNAME}
      - export QUAY_PASSWORD=$${PRODUCTION_QUAY_PASSWORD}
      - export WHITELIST=$${PRODUCTION_WHITELIST}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${PRODUCTION_KEYCLOAK_PROTOCOL}
      - export NGINX_IMAGE=$${PRODUCTION_NGINX_IMAGE}
      - export NGINX_TAG=$${PRODUCTION_NGINX_TAG}
      - export REDIS_URL=$${PRODUCTION_REDIS_URL}
      - export REDIS_TOKEN=$${PRODUCTION_REDIS_TOKEN}
      - export REDIS_SSL=$${PRODUCTION_REDIS_SSL}
      - export GOV_NOTIFY_API_KEY=$${PRODUCTION_GOV_NOTIFY_API_KEY}
      - export GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID=$${PRODUCTION_GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
      - export GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID=$${PRODUCTION_GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}
      - export WWW_URL=$${PRODUCTION_WWW_URL}
      - export WWW_PROTOCOL=$${PRODUCTION_WWW_PROTOCOL}
      - export WWW_UI_PROTOCOL=$${PRODUCTION_WWW_UI_PROTOCOL}
      - export WWW_UI_TXT_PROTOCOL=$${PRODUCTION_WWW_UI_TXT_PROTOCOL}
      - export API_COP_PROTOCOL=$${PRODUCTION_API_COP_PROTOCOL}
      - export API_COP_URL=$${PRODUCTION_API_COP_URL}
      - export API_REF_PROTOCOL=$${PRODUCTION_API_REF_PROTOCOL}
      - export API_REF_URL=$${PRODUCTION_API_REF_URL}
      - export DB_ENGINE_PROTOCOL=$${PRODUCTION_DB_ENGINE_PROTOCOL}
      - export DB_ENGINE_JDBC_PROTOCOL=$${PRODUCTION_DB_ENGINE_JDBC_PROTOCOL}
      - export DB_ENGINE_PORT=$${PRODUCTION_DB_ENGINE_PORT}
      - export DB_ENGINE_HOSTNAME=$${PRODUCTION_DB_ENGINE_HOSTNAME}
      - export DB_ENGINE_OPTIONS=$${PRODUCTION_DB_ENGINE_OPTIONS}
      - export DB_ENGINE_DRIVER=$${PRODUCTION_DB_ENGINE_DRIVER}
      - export DB_ENGINE_TYPE=$${PRODUCTION_DB_ENGINE_TYPE}
      - export DB_ENGINE_JDBC_OPTIONS=$${PRODUCTION_DB_ENGINE_JDBC_OPTIONS}
      - export DB_ENGINE_DEFAULT_USERNAME=$${PRODUCTION_DB_ENGINE_DEFAULT_USERNAME}
      - export DB_ENGINE_DEFAULT_DBNAME=$${PRODUCTION_DB_ENGINE_DEFAULT_DBNAME}
      - export DB_ENGINE_DEFAULT_PASSWORD=$${PRODUCTION_DB_ENGINE_DEFAULT_PASSWORD}
      - export ENGINE_NAME=$${PRODUCTION_ENGINE_NAME}
      - export ENGINE_URL=$${PRODUCTION_ENGINE_URL}
      - export ENGINE_IMAGE=$${PRODUCTION_ENGINE_IMAGE}
      - export ENGINE_KEYCLOAK_CLIENT_ID=$${PRODUCTION_ENGINE_KEYCLOAK_CLIENT_ID}
      - export ENGINE_KEYCLOAK_CLIENT_SECRET=$${PRODUCTION_ENGINE_KEYCLOAK_CLIENT_SECRET}
      - export ENGINE_SPRING_PROFILES_ACTIVE=$${PRODUCTION_ENGINE_SPRING_PROFILES_ACTIVE}
      - export ENGINE_KUBE_NAMESPACE=$${PRODUCTION_ENGINE_KUBE_NAMESPACE}
      - export ENGINE_PORT=$${PRODUCTION_ENGINE_PORT}
      - export ENGINE_JAVA_OPTS=$${PRODUCTION_ENGINE_JAVA_OPTS}
      - export ENGINE_CORS=$${PRODUCTION_ENGINE_CORS}
      - export ENGINE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/nginx-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/certs-configmap.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment

