---
version: '3.7'

volumes:
  postgres_data_workflow:
    driver: local

services:
  postgres_workflow:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_workflow
    volumes:
      - postgres_data_workflow:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: workflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: workflow
    networks:
      - db
    labels:
      - "traefik.enable=false"

  redis_workflow:
    image: redis:5-alpine
    container_name: redis_workflow
    networks:
      - db
    labels:
      - "traefik.enable=false"

  engine:
    build: .
    image: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    restart: on-failure
    container_name: engine
    environment:
      ENGINE_NAME: engine
      ENGINE_JAVA_OPTS: "-XX:PermSize=4096m -Djavax.net.debug=true"
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_PROTOCOL: ${KEYCLOAK_PROTOCOL}
      ENGINE_KEYCLOAK_CLIENT_SECRET: "9d9f6718-90f3-4626-b912-bfcd655ab27f"
      ENGINE_KEYCLOAK_CLIENT_ID: workflow
      ENGINE_SPRING_PROFILES_ACTIVE: local
      DB_ENGINE_DRIVER: ${DB_ENGINE_DRIVER}
      DB_ENGINE_JDBC_PROTOCOL: ${DB_ENGINE_JDBC_PROTOCOL}
      DB_ENGINE_HOSTNAME: ${DB_ENGINE_HOSTNAME}
      DB_ENGINE_DEFAULT_USERNAME: ${DB_ENGINE_DEFAULT_USERNAME}
      DB_ENGINE_DEFAULT_PASSWORD: ${DB_ENGINE_DEFAULT_PASSWORD}
      DB_ENGINE_DEFAULT_DBNAME: ${DB_ENGINE_DEFAULT_DBNAME}
      DB_ENGINE_TYPE: ${DB_ENGINE_TYPE}
      WWW_UI_PROTOCOL: ${WWW_UI_PROTOCOL}
      WWW_UI_TXT_PROTOCOL: ${WWW_UI_TXT_PROTOCOL}
      WWW_URL: ${WWW_PROTOCOL}${WWW_URL}
      API_COP_URL: ${API_COP_PROTOCOL}${API_COP_URL}
      API_REF_URL: ${API_REF_PROTOCOL}${API_REF_URL} 
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TOKEN: ${REDIS_TOKEN}
      GOV_NOTIFY_API_KEY: ${GOV_NOTIFY_API_KEY}
      GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID: ${GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
      GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID: ${GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}
    depends_on:
      - postgres_workflow
      - redis_workflow
    networks:
      - web
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:workflow.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.protocol=http"
      - "traefik.docker.network=web"

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
