---
version: '3.7'

volumes:
  postgres_data_workflow:
    driver: local

services:
  postgres_workflow:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_workflow
    volumes:
      - postgres_data_workflow:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: workflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: workflow
    networks:
      - db
    labels:
      - "traefik.enable=false"

  redis_workflow:
    image: redis:5-alpine
    container_name: redis_workflow
    networks:
      - db
    labels:
      - "traefik.enable=false"

  workflow:
    build: .
    image: quay.io/ukhomeofficedigital/cop-private-workflow-engine
    restart: on-failure
    container_name: workflow
    environment:
      JAVA_OPTS: "-XX:PermSize=4096m -Djavax.net.debug=true"
      ENGINE_DB_DRIVER: org.postgresql.Driver
      CAMUNDA_DB_TYPE: postgres
      KEYCLOAK_REALM: dev
      KEYCLOAK_AUTH_URL: "https://keycloak.lodev.xyz/auth"
      KEYCLOAK_AUTH_SECRET: "9d9f6718-90f3-4626-b912-bfcd655ab27f"
      KEYCLOAK_CLIENT_ID: workflow
      SPRING_PROFILES_ACTIVE: local
      ENGINE_DB_URL: "jdbc:postgresql://postgres_workflow:5432/workflow"
      ENGINE_DB_USERNAME: postgres
      ENGINE_DB_PASSWORD: workflow
      PLATFORM_DATA_URL: "NOTREQUIRED"
      PUBLIC_UI_PROTOCOL: "NOTREQUIRED"
      PUBLIC_UI_TXT_PROTOCOL: "NOTREQUIRED"
      PRIVATE_REDIS_URL: redis_workflow
      PRIVATE_REDIS_PORT: 6379
      PRIVATE_REDIS_TOKEN: null
      GOV_NOTIFY_CLIENT_ID: "NOTREQUIRED"
      GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID: "NOTREQUIRED"
      GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID: "NOTREQUIRED"
    depends_on:
      - postgres_workflow
      - redis_workflow
    networks:
      - web
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:workflow.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.protocol=http"
      - "traefik.docker.network=web"

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
