---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ENGINE_NAME}}
spec:
  selector:
    matchLabels:
      name: {{.ENGINE_NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.ENGINE_NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{.ENGINE_NAME}}-proxy
        image: {{.NGINX_IMAGE}}:{{.NGINX_TAG}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: "100m"
         requests:
          memory: "50Mi"
          cpu: "100m"
        command: ["/bin/bash"]
        args: ["-c", "/bin/cp /mnt/configmap/* /usr/local/openresty/nginx/conf/locations/; cd /usr/local/openresty; /go.sh"]
        env:
        - name: CUSTOM_PROXY_CONFIG
          value: "TRUE"
        - name: CUSTOM_SECURITY_DEFAULTS
          value: "TRUE"
        - name: SERVER_CERT
          value: "/certs/tls.crt"
        - name: SERVER_KEY
          value: "/certs/tls.key"
        - name: SSL_CIPHERS
          value: "ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:AES256+EDH:!aNULL"
        - name: ENABLE_UUID_PARAM
          value: "HEADER"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: PORT_IN_HOST_HEADER
          value: "FALSE"
        - name: ERROR_REDIRECT_CODES
          value: "599"
        - name: ADD_NGINX_SERVER_CFG
          value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        - name: STATSD_METRICS
          value: "FALSE"
        ports:
        - name: https
          containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
          - name: proxyconfigmap
            mountPath: /mnt/configmap
      - name: {{.ENGINE_NAME}}
        image: {{.ENGINE_IMAGE}}:{{.ENGINE_TAG}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        command: ["/bin/bash"]
        args: ["-c", "/usr/bin/run.sh -Djava.security.egd=file:/dev/./urandom -Xms1536m -Xmx1536m -XX:MaxMetaspaceSize=256m -XX:MaxJavaStackTraceDepth=15 -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStore=/etc/keystore/cacerts -jar /app/dist/libs/workflow-engine.jar"]
        resources:
          requests:
            memory: "6144Mi"
            cpu: "4000m"
          limits:
            memory: "6144Mi"
            cpu: "4000m"
        readinessProbe:
          httpGet:
            path: /engine
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
          - name: cacerts
            mountPath: /cacerts
          - name: trustedcerts
            mountPath: /trustedcerts
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "{{.ENGINE_SPRING_PROFILES_ACTIVE}}"
          - name: AWS_REGION
            value: "eu-west-2"
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.ENGINE_NAME}}
                key: awsAccessKeyId
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{.ENGINE_NAME}}
                key: awsSecretAccessKey
          - name: AWS_SECRETS_MANAGER_ENABLED
            value: "true"
      volumes:
      - name: certs
        secret:
          secretName: "{{.ENGINE_NAME}}-pod-cmio"
      - name: trustedcerts
        configMap:
          name: {{.ENGINE_NAME}}-certs
      - name: cacerts
        emptyDir: {}
      - name: proxyconfigmap
        configMap:
          name: {{.ENGINE_NAME}}
