apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: borders-workflow-engine
spec:
  replicas: {{ .WORKFLOW_ENGINE_RELICA_COUNT }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: borders-workflow-engine
      annotations:
        owner: "amin.mohammed-coleman@digital.homeoffice.gov.uk"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: borders-workflow-engine
        image: quay.io/ukhomeofficedigital/borders-workflow-engine:latest
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: {{ .KUBE_CPU_LIMIT }}
            memory: {{ .KUBE_MEMORY_LIMIT }}
        readinessProbe:
          httpGet:
            path: /engine
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
        env:
          # auth configuration
          - name: KEYCLOAK_AUTH_URL
            valueFrom:
              secretKeyRef:
                name: workflow-engine-secrets
                key: auth-server-url
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: workflow-engine-secrets
                key: auth-realm
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: workflow-engine-secrets
                key: auth-client-id
          - name: KEYCLOAK_MGMT_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: workflow-engine-secrets
                key: auth-mgmnt-client-id
          - name: KEYCLOAK_MGMT_USERNAME
            valueFrom:
              secretKeyRef:
                name: workflow-engine-secrets
                key: auth-mgmnt-username
          - name: KEYCLOAK_MGMT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: workflow-engine-secrets
                key: auth-mgmnt-password
         # S3 Configuration
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .ENVIRONMENT }}
          - name: AWS_BPMN_S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: bfarch-{{ .ENVIRONMENT }}-s3-access
                key: access_key_id
          - name: AWS_BPMN_S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: bfarch-{{ .ENVIRONMENT }}-s3-access
                key: secret_access_key
          - name: AWS_BPMN_S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: bfarch-{{ .ENVIRONMENT }}-s3-access
                key: bucket_name
         # DB configuration
          - name: ENGINE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: bfarch-{{ .ENVIRONMENT }}-postgres-rds
                key: port
          - name: ENGINE_DB_URL
            valueFrom:
              secretKeyRef:
                name: bfarch-{{ .ENVIRONMENT }}-postgres-rds
                key: endpoint
          - name: ENGINE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: bfarch-{{.ENVIRONMENT }}-postgres-rds
                key: username
          - name: ENGINE_BD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bfarch-{{.ENVIRONMENT }}-postgres-rds
                key: password
          - name: ENGINE_DB_NAME
            valueFrom:
              secretKeyRef:
                name: bfarch-{{.ENVIRONMENT }}-postgres-rds
                key: db_name
