---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{.ENGINE_NAME}}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
      - port: 443
        protocol: TCP
  podSelector:
    matchLabels:
      name: {{.ENGINE_NAME}}
  policyTypes:
    - Ingress
    - Egress
