---
apiVersion: v1
kind: Secret
metadata:
  name: {{.ENGINE_NAME}}
type: Opaque
data:
  awsAccessKeyId: "{{.ENGINE_AWS_ACCESS_KEY_ID | b64enc }}"
  awsSecretAccessKey: "{{.ENGINE_AWS_SECRET_ACCESS_KEY | b64enc }}"
