---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: borders-workflow-engine
  name: borders-workflow-engine
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: borders-workflow-engine