---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.ENGINE_NAME}}
  name: {{.ENGINE_NAME}}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: {{.ENGINE_NAME}}