camunda:
  bpm:
    process-engine-name: borders
    database:
      type: postgres

spring:
  datasource:
    url: ${ENGINE_DB_URL}
    username: ${ENGINE_DB_USERNAME}
    password: ${ENGINE_BD_PASSWORD}
    name: ${ENGINE_DB_NAME}
    driver-class-name: org.postgresql.Driver
