endpoints:
  enabled: false
  health:
    enabled: true

---

spring:
  profiles: local

camunda:
  bpm:
    process-engine-name: borders
    database:
      type: h2

engine:
  resource:
    location: src/test/resources

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://${ENGINE_DB_URL}:${ENGINE_DB_PORT}/${ENGINE_DB_NAME}
    username: ${ENGINE_DB_USERNAME}
    password: ${ENGINE_BD_PASSWORD}
    driver-class-name: org.postgresql.Driver

camunda:
  bpm:
    process-engine-name: borders
    database:
      type: postgres

engine:
  resource:
    s3:
      accessKey: ${AWS_BPMN_S3_ACCESS_KEY}
      secretKey: ${AWS_BPMN_S3_SECRET_KEY}
      bucketName: ${AWS_BPMN_S3_BUCKET_NAME}
