keycloak:
  auth-server-url: ${KEYCLOAK_URI}
  public-client: false
  realm: ${KEYCLOAK_REALM}
  resource: ${ENGINE_KEYCLOAK_CLIENT_ID}
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  enable-basic-auth: true
  credentials:
    secret: ${ENGINE_KEYCLOAK_CLIENT_SECRET}

encryption:
  keys:
    private-path: ${ENGINE_PRIVATE_DER_PATH}
    public-path:  ${ENGINE_PUBLIC_DER_PATH}

public-ui:
    protocol: ${WWW_UI_PROTOCOL}
    text-protocol: ${WWW_UI_TXT_PROTOCOL}

cors:
  origins: ${ENGINE_CORS}

api-ref:
  url: ${API_REF_URI}

api-cop:
    url: ${API_COP_URI}
    connect-timeout: 5000
    read-timeout: 5000

gov:
  notify:
    api:
      key: ${GOV_NOTIFY_API_KEY}
      notification:
        emailTemplateId: ${GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
        smsTemplateId:  ${GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}

camunda:
  bpm:
    process-engine-name: borders
    database:
      type: ${DB_ENGINE_TYPE}
    deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.cmmn
    - classpath*:**/*.cmmn10.xml
    - classpath*:**/*.cmmn11.xml
    - file:///workflow-resources/bpmn/**/*.bpmn
    - file:///workflow-resources/cmmn/**/*.cmmn
    - file:///workflow-resources/dmn/**/*.dmn

spring:
  datasource:
    driver-class-name: ${DB_ENGINE_DRIVER}
    password: ${DB_ENGINE_DEFAULT_PASSWORD}
    username: ${DB_ENGINE_DEFAULT_USERNAME}
    url: ${DB_ENGINE_URI}
    hikari:
      maximum-pool-size: 30
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSqlLimit: 2048
        prepStmtCacheSize: 250

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  #
  #logging:
  #  pattern:
  #    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{mdcData}] %-5level %logger{36} - %msg%n"
logging:
  pattern:
    level: "%X{mdcData}%5p"
  level:
    org.springframework.web.socket: ERROR



server:
  error:
    whitelabel:
      enabled: false

