endpoints:
  enabled: false
  health:
    enabled: true


keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  public-client: false
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  enable-basic-auth: true
  credentials:
    secret: ${KEYCLOAK_AUTH_SECRET}


prest-url: ${PREST_ENDPOINT_URL}
prest-db: ${TX_DB_NAME}

gov:
  notify:
    api:
      key: ${GOV_NOTIFY_CLIENT_ID}
      notification:
        emailTemplateId: ${GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
        smsTemplateId:  ${GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}


---

spring:
  profiles: local,test

camunda:
  bpm:
    process-engine-name: borders
    database:
      type: h2

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://${ENGINE_DB_URL}:${ENGINE_DB_PORT}/${ENGINE_DB_NAME}
    username: ${ENGINE_DB_USERNAME}
    password: ${ENGINE_BD_PASSWORD}
    driver-class-name: org.postgresql.Driver

camunda:
  bpm:
    process-engine-name: borders
    database:
      type: postgres

